// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyber/examples/proto/examples.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_cyber_2fexamples_2fproto_2fexamples_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_cyber_2fexamples_2fproto_2fexamples_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cyber_2fexamples_2fproto_2fexamples_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_cyber_2fexamples_2fproto_2fexamples_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto;
namespace apollo {
namespace cyber {
namespace examples {
namespace proto {
class Chatter;
class ChatterDefaultTypeInternal;
extern ChatterDefaultTypeInternal _Chatter_default_instance_;
class Driver;
class DriverDefaultTypeInternal;
extern DriverDefaultTypeInternal _Driver_default_instance_;
class SamplesTest1;
class SamplesTest1DefaultTypeInternal;
extern SamplesTest1DefaultTypeInternal _SamplesTest1_default_instance_;
class YUV;
class YUVDefaultTypeInternal;
extern YUVDefaultTypeInternal _YUV_default_instance_;
}  // namespace proto
}  // namespace examples
}  // namespace cyber
}  // namespace apollo
PROTOBUF_NAMESPACE_OPEN
template<> ::apollo::cyber::examples::proto::Chatter* Arena::CreateMaybeMessage<::apollo::cyber::examples::proto::Chatter>(Arena*);
template<> ::apollo::cyber::examples::proto::Driver* Arena::CreateMaybeMessage<::apollo::cyber::examples::proto::Driver>(Arena*);
template<> ::apollo::cyber::examples::proto::SamplesTest1* Arena::CreateMaybeMessage<::apollo::cyber::examples::proto::SamplesTest1>(Arena*);
template<> ::apollo::cyber::examples::proto::YUV* Arena::CreateMaybeMessage<::apollo::cyber::examples::proto::YUV>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace apollo {
namespace cyber {
namespace examples {
namespace proto {

// ===================================================================

class SamplesTest1 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.examples.proto.SamplesTest1) */ {
 public:
  inline SamplesTest1() : SamplesTest1(nullptr) {}
  virtual ~SamplesTest1();

  SamplesTest1(const SamplesTest1& from);
  SamplesTest1(SamplesTest1&& from) noexcept
    : SamplesTest1() {
    *this = ::std::move(from);
  }

  inline SamplesTest1& operator=(const SamplesTest1& from) {
    CopyFrom(from);
    return *this;
  }
  inline SamplesTest1& operator=(SamplesTest1&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SamplesTest1& default_instance();

  static inline const SamplesTest1* internal_default_instance() {
    return reinterpret_cast<const SamplesTest1*>(
               &_SamplesTest1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SamplesTest1& a, SamplesTest1& b) {
    a.Swap(&b);
  }
  inline void Swap(SamplesTest1* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SamplesTest1* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SamplesTest1* New() const final {
    return CreateMaybeMessage<SamplesTest1>(nullptr);
  }

  SamplesTest1* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SamplesTest1>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SamplesTest1& from);
  void MergeFrom(const SamplesTest1& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SamplesTest1* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.examples.proto.SamplesTest1";
  }
  protected:
  explicit SamplesTest1(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto);
    return ::descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClassNameFieldNumber = 1,
    kCaseNameFieldNumber = 2,
  };
  // optional string class_name = 1;
  bool has_class_name() const;
  private:
  bool _internal_has_class_name() const;
  public:
  void clear_class_name();
  const std::string& class_name() const;
  void set_class_name(const std::string& value);
  void set_class_name(std::string&& value);
  void set_class_name(const char* value);
  void set_class_name(const char* value, size_t size);
  std::string* mutable_class_name();
  std::string* release_class_name();
  void set_allocated_class_name(std::string* class_name);
  private:
  const std::string& _internal_class_name() const;
  void _internal_set_class_name(const std::string& value);
  std::string* _internal_mutable_class_name();
  public:

  // optional string case_name = 2;
  bool has_case_name() const;
  private:
  bool _internal_has_case_name() const;
  public:
  void clear_case_name();
  const std::string& case_name() const;
  void set_case_name(const std::string& value);
  void set_case_name(std::string&& value);
  void set_case_name(const char* value);
  void set_case_name(const char* value, size_t size);
  std::string* mutable_case_name();
  std::string* release_case_name();
  void set_allocated_case_name(std::string* case_name);
  private:
  const std::string& _internal_case_name() const;
  void _internal_set_case_name(const std::string& value);
  std::string* _internal_mutable_case_name();
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.examples.proto.SamplesTest1)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr class_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr case_name_;
  friend struct ::TableStruct_cyber_2fexamples_2fproto_2fexamples_2eproto;
};
// -------------------------------------------------------------------

class Chatter PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.examples.proto.Chatter) */ {
 public:
  inline Chatter() : Chatter(nullptr) {}
  virtual ~Chatter();

  Chatter(const Chatter& from);
  Chatter(Chatter&& from) noexcept
    : Chatter() {
    *this = ::std::move(from);
  }

  inline Chatter& operator=(const Chatter& from) {
    CopyFrom(from);
    return *this;
  }
  inline Chatter& operator=(Chatter&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Chatter& default_instance();

  static inline const Chatter* internal_default_instance() {
    return reinterpret_cast<const Chatter*>(
               &_Chatter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Chatter& a, Chatter& b) {
    a.Swap(&b);
  }
  inline void Swap(Chatter* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Chatter* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Chatter* New() const final {
    return CreateMaybeMessage<Chatter>(nullptr);
  }

  Chatter* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Chatter>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Chatter& from);
  void MergeFrom(const Chatter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Chatter* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.examples.proto.Chatter";
  }
  protected:
  explicit Chatter(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto);
    return ::descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 4,
    kTimestampFieldNumber = 1,
    kLidarTimestampFieldNumber = 2,
    kSeqFieldNumber = 3,
  };
  // optional bytes content = 4;
  bool has_content() const;
  private:
  bool _internal_has_content() const;
  public:
  void clear_content();
  const std::string& content() const;
  void set_content(const std::string& value);
  void set_content(std::string&& value);
  void set_content(const char* value);
  void set_content(const void* value, size_t size);
  std::string* mutable_content();
  std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // optional uint64 timestamp = 1;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 lidar_timestamp = 2;
  bool has_lidar_timestamp() const;
  private:
  bool _internal_has_lidar_timestamp() const;
  public:
  void clear_lidar_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 lidar_timestamp() const;
  void set_lidar_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_lidar_timestamp() const;
  void _internal_set_lidar_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 seq = 3;
  bool has_seq() const;
  private:
  bool _internal_has_seq() const;
  public:
  void clear_seq();
  ::PROTOBUF_NAMESPACE_ID::uint64 seq() const;
  void set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_seq() const;
  void _internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.examples.proto.Chatter)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 lidar_timestamp_;
  ::PROTOBUF_NAMESPACE_ID::uint64 seq_;
  friend struct ::TableStruct_cyber_2fexamples_2fproto_2fexamples_2eproto;
};
// -------------------------------------------------------------------

class Driver PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.examples.proto.Driver) */ {
 public:
  inline Driver() : Driver(nullptr) {}
  virtual ~Driver();

  Driver(const Driver& from);
  Driver(Driver&& from) noexcept
    : Driver() {
    *this = ::std::move(from);
  }

  inline Driver& operator=(const Driver& from) {
    CopyFrom(from);
    return *this;
  }
  inline Driver& operator=(Driver&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Driver& default_instance();

  static inline const Driver* internal_default_instance() {
    return reinterpret_cast<const Driver*>(
               &_Driver_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Driver& a, Driver& b) {
    a.Swap(&b);
  }
  inline void Swap(Driver* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Driver* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Driver* New() const final {
    return CreateMaybeMessage<Driver>(nullptr);
  }

  Driver* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Driver>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Driver& from);
  void MergeFrom(const Driver& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Driver* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.examples.proto.Driver";
  }
  protected:
  explicit Driver(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto);
    return ::descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 1,
    kMsgIdFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // optional string content = 1;
  bool has_content() const;
  private:
  bool _internal_has_content() const;
  public:
  void clear_content();
  const std::string& content() const;
  void set_content(const std::string& value);
  void set_content(std::string&& value);
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  std::string* mutable_content();
  std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // optional uint64 msg_id = 2;
  bool has_msg_id() const;
  private:
  bool _internal_has_msg_id() const;
  public:
  void clear_msg_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_id() const;
  void set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_msg_id() const;
  void _internal_set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 timestamp = 3;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.examples.proto.Driver)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  friend struct ::TableStruct_cyber_2fexamples_2fproto_2fexamples_2eproto;
};
// -------------------------------------------------------------------

class YUV PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.examples.proto.YUV) */ {
 public:
  inline YUV() : YUV(nullptr) {}
  virtual ~YUV();

  YUV(const YUV& from);
  YUV(YUV&& from) noexcept
    : YUV() {
    *this = ::std::move(from);
  }

  inline YUV& operator=(const YUV& from) {
    CopyFrom(from);
    return *this;
  }
  inline YUV& operator=(YUV&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const YUV& default_instance();

  static inline const YUV* internal_default_instance() {
    return reinterpret_cast<const YUV*>(
               &_YUV_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(YUV& a, YUV& b) {
    a.Swap(&b);
  }
  inline void Swap(YUV* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(YUV* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline YUV* New() const final {
    return CreateMaybeMessage<YUV>(nullptr);
  }

  YUV* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<YUV>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const YUV& from);
  void MergeFrom(const YUV& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(YUV* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "apollo.cyber.examples.proto.YUV";
  }
  protected:
  explicit YUV(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto);
    return ::descriptor_table_cyber_2fexamples_2fproto_2fexamples_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kContentFieldNumber = 1,
    kYPathFieldNumber = 4,
    kUvPathFieldNumber = 5,
    kMsgIdFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // optional string content = 1;
  bool has_content() const;
  private:
  bool _internal_has_content() const;
  public:
  void clear_content();
  const std::string& content() const;
  void set_content(const std::string& value);
  void set_content(std::string&& value);
  void set_content(const char* value);
  void set_content(const char* value, size_t size);
  std::string* mutable_content();
  std::string* release_content();
  void set_allocated_content(std::string* content);
  private:
  const std::string& _internal_content() const;
  void _internal_set_content(const std::string& value);
  std::string* _internal_mutable_content();
  public:

  // optional string y_path = 4;
  bool has_y_path() const;
  private:
  bool _internal_has_y_path() const;
  public:
  void clear_y_path();
  const std::string& y_path() const;
  void set_y_path(const std::string& value);
  void set_y_path(std::string&& value);
  void set_y_path(const char* value);
  void set_y_path(const char* value, size_t size);
  std::string* mutable_y_path();
  std::string* release_y_path();
  void set_allocated_y_path(std::string* y_path);
  private:
  const std::string& _internal_y_path() const;
  void _internal_set_y_path(const std::string& value);
  std::string* _internal_mutable_y_path();
  public:

  // optional string uv_path = 5;
  bool has_uv_path() const;
  private:
  bool _internal_has_uv_path() const;
  public:
  void clear_uv_path();
  const std::string& uv_path() const;
  void set_uv_path(const std::string& value);
  void set_uv_path(std::string&& value);
  void set_uv_path(const char* value);
  void set_uv_path(const char* value, size_t size);
  std::string* mutable_uv_path();
  std::string* release_uv_path();
  void set_allocated_uv_path(std::string* uv_path);
  private:
  const std::string& _internal_uv_path() const;
  void _internal_set_uv_path(const std::string& value);
  std::string* _internal_mutable_uv_path();
  public:

  // optional uint64 msg_id = 2;
  bool has_msg_id() const;
  private:
  bool _internal_has_msg_id() const;
  public:
  void clear_msg_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_id() const;
  void set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_msg_id() const;
  void _internal_set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // optional uint64 timestamp = 3;
  bool has_timestamp() const;
  private:
  bool _internal_has_timestamp() const;
  public:
  void clear_timestamp();
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp() const;
  void set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_timestamp() const;
  void _internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:apollo.cyber.examples.proto.YUV)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr content_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr y_path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uv_path_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 timestamp_;
  friend struct ::TableStruct_cyber_2fexamples_2fproto_2fexamples_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SamplesTest1

// optional string class_name = 1;
inline bool SamplesTest1::_internal_has_class_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SamplesTest1::has_class_name() const {
  return _internal_has_class_name();
}
inline void SamplesTest1::clear_class_name() {
  class_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SamplesTest1::class_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SamplesTest1.class_name)
  return _internal_class_name();
}
inline void SamplesTest1::set_class_name(const std::string& value) {
  _internal_set_class_name(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SamplesTest1.class_name)
}
inline std::string* SamplesTest1::mutable_class_name() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.examples.proto.SamplesTest1.class_name)
  return _internal_mutable_class_name();
}
inline const std::string& SamplesTest1::_internal_class_name() const {
  return class_name_.Get();
}
inline void SamplesTest1::_internal_set_class_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SamplesTest1::set_class_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.examples.proto.SamplesTest1.class_name)
}
inline void SamplesTest1::set_class_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  class_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.examples.proto.SamplesTest1.class_name)
}
inline void SamplesTest1::set_class_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  class_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.examples.proto.SamplesTest1.class_name)
}
inline std::string* SamplesTest1::_internal_mutable_class_name() {
  _has_bits_[0] |= 0x00000001u;
  return class_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SamplesTest1::release_class_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.examples.proto.SamplesTest1.class_name)
  if (!_internal_has_class_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return class_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SamplesTest1::set_allocated_class_name(std::string* class_name) {
  if (class_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  class_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), class_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.examples.proto.SamplesTest1.class_name)
}

// optional string case_name = 2;
inline bool SamplesTest1::_internal_has_case_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SamplesTest1::has_case_name() const {
  return _internal_has_case_name();
}
inline void SamplesTest1::clear_case_name() {
  case_name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& SamplesTest1::case_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.SamplesTest1.case_name)
  return _internal_case_name();
}
inline void SamplesTest1::set_case_name(const std::string& value) {
  _internal_set_case_name(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.SamplesTest1.case_name)
}
inline std::string* SamplesTest1::mutable_case_name() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.examples.proto.SamplesTest1.case_name)
  return _internal_mutable_case_name();
}
inline const std::string& SamplesTest1::_internal_case_name() const {
  return case_name_.Get();
}
inline void SamplesTest1::_internal_set_case_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  case_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SamplesTest1::set_case_name(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  case_name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.examples.proto.SamplesTest1.case_name)
}
inline void SamplesTest1::set_case_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  case_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.examples.proto.SamplesTest1.case_name)
}
inline void SamplesTest1::set_case_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  case_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.examples.proto.SamplesTest1.case_name)
}
inline std::string* SamplesTest1::_internal_mutable_case_name() {
  _has_bits_[0] |= 0x00000002u;
  return case_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SamplesTest1::release_case_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.examples.proto.SamplesTest1.case_name)
  if (!_internal_has_case_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return case_name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SamplesTest1::set_allocated_case_name(std::string* case_name) {
  if (case_name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  case_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), case_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.examples.proto.SamplesTest1.case_name)
}

// -------------------------------------------------------------------

// Chatter

// optional uint64 timestamp = 1;
inline bool Chatter::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Chatter::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void Chatter::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chatter::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chatter::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.Chatter.timestamp)
  return _internal_timestamp();
}
inline void Chatter::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  timestamp_ = value;
}
inline void Chatter::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.Chatter.timestamp)
}

// optional uint64 lidar_timestamp = 2;
inline bool Chatter::_internal_has_lidar_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Chatter::has_lidar_timestamp() const {
  return _internal_has_lidar_timestamp();
}
inline void Chatter::clear_lidar_timestamp() {
  lidar_timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chatter::_internal_lidar_timestamp() const {
  return lidar_timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chatter::lidar_timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.Chatter.lidar_timestamp)
  return _internal_lidar_timestamp();
}
inline void Chatter::_internal_set_lidar_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  lidar_timestamp_ = value;
}
inline void Chatter::set_lidar_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_lidar_timestamp(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.Chatter.lidar_timestamp)
}

// optional uint64 seq = 3;
inline bool Chatter::_internal_has_seq() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Chatter::has_seq() const {
  return _internal_has_seq();
}
inline void Chatter::clear_seq() {
  seq_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chatter::_internal_seq() const {
  return seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Chatter::seq() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.Chatter.seq)
  return _internal_seq();
}
inline void Chatter::_internal_set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  seq_ = value;
}
inline void Chatter::set_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.Chatter.seq)
}

// optional bytes content = 4;
inline bool Chatter::_internal_has_content() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Chatter::has_content() const {
  return _internal_has_content();
}
inline void Chatter::clear_content() {
  content_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Chatter::content() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.Chatter.content)
  return _internal_content();
}
inline void Chatter::set_content(const std::string& value) {
  _internal_set_content(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.Chatter.content)
}
inline std::string* Chatter::mutable_content() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.examples.proto.Chatter.content)
  return _internal_mutable_content();
}
inline const std::string& Chatter::_internal_content() const {
  return content_.Get();
}
inline void Chatter::_internal_set_content(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Chatter::set_content(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.examples.proto.Chatter.content)
}
inline void Chatter::set_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.examples.proto.Chatter.content)
}
inline void Chatter::set_content(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.examples.proto.Chatter.content)
}
inline std::string* Chatter::_internal_mutable_content() {
  _has_bits_[0] |= 0x00000001u;
  return content_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Chatter::release_content() {
  // @@protoc_insertion_point(field_release:apollo.cyber.examples.proto.Chatter.content)
  if (!_internal_has_content()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return content_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Chatter::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  content_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.examples.proto.Chatter.content)
}

// -------------------------------------------------------------------

// Driver

// optional string content = 1;
inline bool Driver::_internal_has_content() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Driver::has_content() const {
  return _internal_has_content();
}
inline void Driver::clear_content() {
  content_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Driver::content() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.Driver.content)
  return _internal_content();
}
inline void Driver::set_content(const std::string& value) {
  _internal_set_content(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.Driver.content)
}
inline std::string* Driver::mutable_content() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.examples.proto.Driver.content)
  return _internal_mutable_content();
}
inline const std::string& Driver::_internal_content() const {
  return content_.Get();
}
inline void Driver::_internal_set_content(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Driver::set_content(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.examples.proto.Driver.content)
}
inline void Driver::set_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.examples.proto.Driver.content)
}
inline void Driver::set_content(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.examples.proto.Driver.content)
}
inline std::string* Driver::_internal_mutable_content() {
  _has_bits_[0] |= 0x00000001u;
  return content_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Driver::release_content() {
  // @@protoc_insertion_point(field_release:apollo.cyber.examples.proto.Driver.content)
  if (!_internal_has_content()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return content_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Driver::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  content_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.examples.proto.Driver.content)
}

// optional uint64 msg_id = 2;
inline bool Driver::_internal_has_msg_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Driver::has_msg_id() const {
  return _internal_has_msg_id();
}
inline void Driver::clear_msg_id() {
  msg_id_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Driver::_internal_msg_id() const {
  return msg_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Driver::msg_id() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.Driver.msg_id)
  return _internal_msg_id();
}
inline void Driver::_internal_set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000002u;
  msg_id_ = value;
}
inline void Driver::set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.Driver.msg_id)
}

// optional uint64 timestamp = 3;
inline bool Driver::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Driver::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void Driver::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Driver::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Driver::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.Driver.timestamp)
  return _internal_timestamp();
}
inline void Driver::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000004u;
  timestamp_ = value;
}
inline void Driver::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.Driver.timestamp)
}

// -------------------------------------------------------------------

// YUV

// optional string content = 1;
inline bool YUV::_internal_has_content() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool YUV::has_content() const {
  return _internal_has_content();
}
inline void YUV::clear_content() {
  content_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& YUV::content() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.YUV.content)
  return _internal_content();
}
inline void YUV::set_content(const std::string& value) {
  _internal_set_content(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.YUV.content)
}
inline std::string* YUV::mutable_content() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.examples.proto.YUV.content)
  return _internal_mutable_content();
}
inline const std::string& YUV::_internal_content() const {
  return content_.Get();
}
inline void YUV::_internal_set_content(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void YUV::set_content(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.examples.proto.YUV.content)
}
inline void YUV::set_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.examples.proto.YUV.content)
}
inline void YUV::set_content(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  content_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.examples.proto.YUV.content)
}
inline std::string* YUV::_internal_mutable_content() {
  _has_bits_[0] |= 0x00000001u;
  return content_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* YUV::release_content() {
  // @@protoc_insertion_point(field_release:apollo.cyber.examples.proto.YUV.content)
  if (!_internal_has_content()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return content_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void YUV::set_allocated_content(std::string* content) {
  if (content != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  content_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), content,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.examples.proto.YUV.content)
}

// optional uint64 msg_id = 2;
inline bool YUV::_internal_has_msg_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool YUV::has_msg_id() const {
  return _internal_has_msg_id();
}
inline void YUV::clear_msg_id() {
  msg_id_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 YUV::_internal_msg_id() const {
  return msg_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 YUV::msg_id() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.YUV.msg_id)
  return _internal_msg_id();
}
inline void YUV::_internal_set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000008u;
  msg_id_ = value;
}
inline void YUV::set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_msg_id(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.YUV.msg_id)
}

// optional uint64 timestamp = 3;
inline bool YUV::_internal_has_timestamp() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool YUV::has_timestamp() const {
  return _internal_has_timestamp();
}
inline void YUV::clear_timestamp() {
  timestamp_ = PROTOBUF_ULONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 YUV::_internal_timestamp() const {
  return timestamp_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 YUV::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.YUV.timestamp)
  return _internal_timestamp();
}
inline void YUV::_internal_set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _has_bits_[0] |= 0x00000010u;
  timestamp_ = value;
}
inline void YUV::set_timestamp(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.YUV.timestamp)
}

// optional string y_path = 4;
inline bool YUV::_internal_has_y_path() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool YUV::has_y_path() const {
  return _internal_has_y_path();
}
inline void YUV::clear_y_path() {
  y_path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& YUV::y_path() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.YUV.y_path)
  return _internal_y_path();
}
inline void YUV::set_y_path(const std::string& value) {
  _internal_set_y_path(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.YUV.y_path)
}
inline std::string* YUV::mutable_y_path() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.examples.proto.YUV.y_path)
  return _internal_mutable_y_path();
}
inline const std::string& YUV::_internal_y_path() const {
  return y_path_.Get();
}
inline void YUV::_internal_set_y_path(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  y_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void YUV::set_y_path(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  y_path_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.examples.proto.YUV.y_path)
}
inline void YUV::set_y_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  y_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.examples.proto.YUV.y_path)
}
inline void YUV::set_y_path(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  y_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.examples.proto.YUV.y_path)
}
inline std::string* YUV::_internal_mutable_y_path() {
  _has_bits_[0] |= 0x00000002u;
  return y_path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* YUV::release_y_path() {
  // @@protoc_insertion_point(field_release:apollo.cyber.examples.proto.YUV.y_path)
  if (!_internal_has_y_path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return y_path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void YUV::set_allocated_y_path(std::string* y_path) {
  if (y_path != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  y_path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), y_path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.examples.proto.YUV.y_path)
}

// optional string uv_path = 5;
inline bool YUV::_internal_has_uv_path() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool YUV::has_uv_path() const {
  return _internal_has_uv_path();
}
inline void YUV::clear_uv_path() {
  uv_path_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& YUV::uv_path() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.examples.proto.YUV.uv_path)
  return _internal_uv_path();
}
inline void YUV::set_uv_path(const std::string& value) {
  _internal_set_uv_path(value);
  // @@protoc_insertion_point(field_set:apollo.cyber.examples.proto.YUV.uv_path)
}
inline std::string* YUV::mutable_uv_path() {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.examples.proto.YUV.uv_path)
  return _internal_mutable_uv_path();
}
inline const std::string& YUV::_internal_uv_path() const {
  return uv_path_.Get();
}
inline void YUV::_internal_set_uv_path(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  uv_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void YUV::set_uv_path(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  uv_path_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.examples.proto.YUV.uv_path)
}
inline void YUV::set_uv_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  uv_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:apollo.cyber.examples.proto.YUV.uv_path)
}
inline void YUV::set_uv_path(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  uv_path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.examples.proto.YUV.uv_path)
}
inline std::string* YUV::_internal_mutable_uv_path() {
  _has_bits_[0] |= 0x00000004u;
  return uv_path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* YUV::release_uv_path() {
  // @@protoc_insertion_point(field_release:apollo.cyber.examples.proto.YUV.uv_path)
  if (!_internal_has_uv_path()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return uv_path_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void YUV::set_allocated_uv_path(std::string* uv_path) {
  if (uv_path != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  uv_path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uv_path,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.examples.proto.YUV.uv_path)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace examples
}  // namespace cyber
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_cyber_2fexamples_2fproto_2fexamples_2eproto
